### ISSUE TITLE
fix the blinking tiles when loading on composer

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1419] opened 2016-03-31 15:14 UTC
when features are loaded during playback for the first time, they appear like they're blinking.  just make it more pleasing to the eyes. Cases like spread/growth or movement don't really look compelling because the blinking effect is too distracting

**Comment by jonpmarino** [comment] 2016-05-31 15:32
duplicate of #543

**Closed as completed by jonpmarino** 2016-05-31 15:32 UTC
