### ISSUE TITLE
Revert changes doesn't work

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1472] opened 2016-04-18 15:23 UTC

**Comment by JWileczek** [comment] 2016-04-20 14:54
This should be up and working on demo, if someone could confirm and close. I just used the walmart layer to test this earlier.

**Comment by jonpmarino** [comment] 2016-04-20 15:40
@JWileczek looks like it works great! One thing i noticed. When I create a new feature, it logs it as Anonymous (I am logged in as Jon Demo). But when I revert it shows my name Jon Demo in the history log. It looks like it captured your name for both create and revert, though.
![revert_grab](https://cloud.githubusercontent.com/assets/2573761/14680810/9cbf4ae2-06ec-11e6-950c-7dd32c34b32a.jpg)

**Comment by JWileczek** [comment] 2016-04-20 17:41
@jonpmarino I'm not sure why it wouldn't capture your name on create unless you don't have the first/last name set. I just made sure my account info was set and the account was confirmed.

**Comment by jonpmarino** [comment] 2016-04-20 17:56
@JWileczek all good. I do have the first/last set on that account, but could be something with me. @reynalddizon will test and others. But lets close this issue as revert is clearly working well!

**Closed as completed by jonpmarino** 2016-04-20 17:56 UTC

**Comment by jonpmarino** [comment] 2016-04-20 18:13
@reynalddizon confirms it works for him. Proper names show up. so will assume its an issue with Jon Demo.
