### ISSUE TITLE
"Map Save Failed" error appears shortly after saving properties to begin a new story

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1530] opened 2016-04-29 13:55 UTC
on beta. Pops up automatically, not in response to a click.

![map_save_failed](https://cloud.githubusercontent.com/assets/2573761/14918177/783c7428-0df0-11e6-9d0b-59189db8f16e.jpg)

**Comment by JWileczek** [comment] 2016-05-27 17:31
Have not experienced these errors since they were added. Closing can be reopened if there are more consistent failures and reproducible errors

**Closed as completed by JWileczek** 2016-05-27 17:31 UTC
