### ISSUE TITLE
Wysiwyg editor or clear guidance on codes for Journal

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1034] opened 2015-06-18 19:25 UTC
Journal entry writers need to know how to add bold, italics, hyperlink, images, videos, etc to their journal entries. Basic blog entry actions.

**Comment by travislbrundage** [comment] 2015-06-24 07:12
Duplicate of #1024?

**Comment by garnertb** [comment] 2015-06-27 23:13
Closing, dup of #1024.

**Closed as completed by garnertb** 2015-06-27 23:13 UTC
