### ISSUE TITLE
Modals for Upload, Create and Append

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1662] opened 2016-06-30 16:45 UTC
[append_storylayer.pdf](https://github.com/MapStory/mapstory/files/341955/append_storylayer.pdf)
[create_storylayer.pdf](https://github.com/MapStory/mapstory/files/341956/create_storylayer.pdf)
[upload_storylayer.pdf](https://github.com/MapStory/mapstory/files/341957/upload_storylayer.pdf)

**Comment by glynnis** [comment] 2016-12-16 22:51
Closing this since links are broken. 

If this is still relevant and can be reproduced, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.

**Closed as completed by glynnis** 2016-12-16 22:51 UTC
