### ISSUE TITLE
Handle metadata in the new uploader.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1265] opened 2015-12-16 16:52 UTC

**Comment by jonpmarino** [comment] 2015-12-30 17:05
closing since its a duplicate of #1279

**Comment by garnertb** [comment] 2015-12-30 17:12
These are actually a bit different.  This issue refers to metadata included in an upload wheras #1279 refers to handling metadata post upload.

**Comment by rob-metalinkage** [comment] 2016-03-15 23:15
How is the new uploader code base updated? (in available instructions its pulled in read-only from git (https://github.com/ProminentEdge/django-osgeo-importer).  Will this work require a fork? If so - please add this as a separate task so I can follow progress and I'll update the docs to help a developer set up the codebase properly.)

My subproject needs to capture metadata during upload - so keen to understand plan here and see how configurable and extensible the solution is.  The metadata I need to capture are things such as what type of feature is in the layer (Administrative boundary etc - Feature type - from list we will maintain - and what namespace labels and codes in fields might be (e.g. identify ISO 3 -letter country codes) - and what language labels might be,  Each of these will have a lookup function with three layers : mapstory preferred, typical, search the full list and finally add a new option. Possibly I'll need to clone the entire wizard and put the user through an additional process - but if the workflow has pluggable handlers or extension points.

**Comment by ChristopherTucker** [comment] 2016-03-16 01:27
Tyler owns the uploader right now.  We have some work that others are doing
right now to upgrade the raster support, etc.

We have had a metadata editor that users could use to author metadata
documents for their dataset.  I am not sure whether it has been completely
migrated to the new build.  It is ISO19115/19139 in the background.  We do
not yet let users upload metadata documents with their data.  If you have
special fields that must be exposed in the metadata editor, we can talk
about that.

On Tue, Mar 15, 2016 at 7:15 PM, rob-metalinkage notifications@github.com
wrote:

> How is the new uploader code base updated? (in available instructions its
> pulled in read-only from git - will this work require a fork? If so -
> please add this as a separate task so I can follow progress and I'll update
> the docs to help a developer set up the codebase properly.)
> 
> My subproject needs to capture metadata during upload - so keen to
> understand plan here and see how configurable and extensible the solution
> is. The metadata I need to capture are things such as what type of feature
> is in the layer (Administrative boundary etc - Feature type - from list we
> will maintain - and what namespace labels and codes in fields might be
> (e.g. identify ISO 3 -letter country codes) - and what language labels
> might be, Each of these will have a lookup function with three layers :
> mapstory preferred, typical, search the full list and finally add a new
> option. Possibly I'll need to clone the entire wizard and put the user
> through an additional process - but if the workflow has pluggable handlers
> or extension points.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MapStory/mapstory/issues/1265#issuecomment-197065028

## 

Chris
703-981-9373

**Comment by rob-metalinkage** [comment] 2016-03-16 04:30
If I can get pointed to the implementation and know the directions taken I can try to work with it - I'm more inclined to try to capture as much as possible during wizard workflows where the payoff for the use can be made explicit (tell us what namespace your place identifiers come from so we can make your map visible from other related stories.) - that said it may be useful to have a load config from file option - then we can start getting all the data together before worrying about any UI design. Can the metadata editor handle multiple file types - each with a handler - so I could write a handler for and extensible semantic approach to metadata and use that in the short term?

**Comment by jj0hns0n** [comment] 2016-03-16 04:32
Rob, lets setup a call with the 2 of us and @garnertb and we can go over
the specifics.

**Comment by rob-metalinkage** [comment] 2016-03-16 04:50
Sweet - it must be late for you there now - som maybe tomorrow afternoon
(my morning will work - anytime after 7am Sydney (currently still in DST at
GMT+11)

**Comment by glynnis** [comment] 2016-12-16 22:48
Closing this. If this is still relevant, please create a new issue with more detail at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.

**Closed as completed by glynnis** 2016-12-16 22:48 UTC
Labels: Needs More Info, Idea for Discussion
