### ISSUE TITLE
Profiles and Community

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1191] opened 2015-10-02 16:03 UTC
#### Profile Page
- [ ] Add Education, Skills, Interests (tags) on the left sidebar.
- [ ] Favorites tab should display Cards instead of a list, for consistency.
- [ ] Send notification emails to users for: recent edits, recent comments, recent flags, new mapstories created using the user's storylayers.

**Comment by jonpmarino** [comment] 2016-02-22 19:23
Closing since now duplicate of #1302

**Closed as completed by jonpmarino** 2016-02-22 19:23 UTC
