### ISSUE TITLE
Full screen > Embed View interaction

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1334] opened 2016-02-15 20:36 UTC
We need a way to switch between full screen and embed, as we had on retro.mapstory.org. 

Example on this StoryLayer > http://mapstory.org/layers/geonode:birds_test

Then replace mapstory map client for storylayers too

**Comment by travislbrundage** [comment] 2016-02-24 01:30
I've gotten a branch that's taken this pretty close to working: https://github.com/travislbrundage/mapstory-geonode/tree/feb26-wip

I have it set for now so that pressing the enter key enters fullscreen mode, and this works fine. I've also added the button on the front end, and this mostly works, except for some reason it's not loading the glyphicon correctly.

The bigger problem though is that I'm having trouble hooking up the button to the javascript fullscreen functionality. Essentially, the problem is this. The HTML to add the button on the front end must reside in the `viewer.html` in order to appear in the map area (as far as I am currently able, anyway). However, the javascript to make the map fullscreen must reside externally because it acts upon the element containing it, `embedded_map`. This is in the `detail_base.html` file, though I have found the javascript can also be included in the `map_include.html` file. Essentially, the javascript for going fullscreen needs to act on the containing element, ergo it needs to be able to see the containing element. If I put the javascript in `viewer.html` or `viewer.js`, it is now embedded within the map itself, so it cannot "see" the `embedded_map` DOM element. But putting the javascript outside in `detail_base.html` or `map_include.html` makes it inaccessible to the added button. If I try to set it to call the function upon clicking, it will just give an `Uncaught Reference Error: toggleFullScreen()`.

So I can't put the HTML and JavaScript together to play, because either the HTML won't "see" the JavaScript function, or the JavaScript won't "see" the `embedded_map` element. This is where I'm currently stuck.

**Comment by davisc** [comment] 2016-02-24 15:23
@travislbrundage Good news I was able to add your code to https://github.com/MapStory/story-tools/commit/f07a665b278978c9451ea5537e2724044aa6a113 and get it working. 90% solution since there are changes that need to be applied to mapstory-geonode templates. For it to work within an iFrame, the following property must be set `allowFullScreen="true"`.

To access the div within the iframe, try this:

`
$(document).ready(function(){
    var div_inside_frame = $('#viewer-frame').contents().find('div#story-viewer');
});
`

**Comment by davisc** [comment] 2016-02-26 17:18
Fixed in https://github.com/MapStory/mapstory-geonode/commit/c6a7c47b9fefb35df2d34828db9217027f2fc735 and https://github.com/MapStory/story-tools/commit/c880d1a7cb19ed31513b0a3969c7c4a2668f9080

**Closed as completed** 2016-02-26 17:20 UTC
