### ISSUE TITLE
Embed link on new mapstory detail page needs to be fixed

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1498] opened 2016-04-25 16:46 UTC
Grabbing the iframe embed of a new mapstory show's up like this on the embed:

![grabembed](https://cloud.githubusercontent.com/assets/2573761/14791382/aa4e645e-0ae3-11e6-8627-e717a29f39e3.jpg)

**Comment by travislbrundage** [comment] 2016-05-02 18:55
Duplicate of #1316 and fixed anyway

**Closed as completed by travislbrundage** 2016-05-02 18:55 UTC
